//import banner from 'rollup-plugin-banner';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import scss from 'rollup-plugin-scss'

// const bannerText = [
//     'EdgeRouter Throughput',
//     '<%= pkg.description %>',
//     '',
//     'Version <%= pkg.version %>',
//     'By <%= pkg.author %>',
//     '',
//     'License <%= pkg.license %>',
//     '',
//     'This is an autogenerated file. DO NOT EDIT!',
// ].join('\n');

export default [
    {
        input: './src/MMM-PrometheusAlerts.ts',
        plugins: [
            typescript(),
            resolve(),
            commonjs(),
            scss({
                fileName: 'MMM-PrometheusAlerts.css'
            })
        ],
        output: {
            file: './MMM-PrometheusAlerts.js',
            format: 'iife',
        },
    }, {
        input: './src/node_helper.ts',
        plugins: [
            typescript()
        ],
        output: {
            file: './node_helper.js',
            format: 'umd',
        },
    },
]