# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    # run builds on every branch, and PRs to main.
    branches:
      - "**"
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout MagicMirror repo
        uses: actions/checkout@v3
        with:
          repository: MichMich/MagicMirror
          path: MagicMirror

      - name: Checkout Module repo
        uses: actions/checkout@v3
        with:
          path: MagicMirror/modules/MMM-PrometheusAlerts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MagicMirror
        run: |
          cd MagicMirror
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm ci

      - name: Run tests
        run: |
          cd MagicMirror/modules/MMM-PrometheusAlerts
          npm install
          npm run test-ci
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        if: ${{ matrix.node-version == '20.x' }}
        with:
          projectBaseDir: MagicMirror/modules/MMM-PrometheusAlerts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
